import { useTranslation } from "next-i18next";
import Head from "next/head";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetStaticPropsContext } from 'next';
import styles from '@/styles/pages/about.module.scss';
import CEOImg from '../../public/static/ceo.jpg'
import Image from "next/image";


export default function About() {

    const { t: translate } = useTranslation('header')

    return (
        <>
            <Head>
                <title>GEorGE • Cosmetic • About</title>
                <link rel="icon" href="/george.ico" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charSet="UTF-8" />
                <meta name="az197" content="GEorGe Cosmetics" />
                {/* Keywords (specify relevant keywords related to your web page content for SEO): */}
                <meta name="keywords" content="keyword1, keyword2, keyword3" />
                <meta name="theme-color" content="#191716" />
            </Head>

            <div className={styles.AboutPageWrapper}>

                <section className={styles.AboutPageSection}>

                    <div className={styles.AboutProfile}>

                        <div className={styles.AboutCeoImage}>
                            <Image src={CEOImg} alt="ceo" />
                        </div>


                        <div className={styles.AboutCeoName}>
                            <h2>Allan Keonick</h2>
                            <h4>FOUNDER AND CEO</h4>
                        </div>
                    </div>

                    <div className={styles.AboutTextContainer}>

                        <div className={styles.AbouText}>
                            <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, dicta.</h3>
                            <p className={styles.Par1}>
                                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti nobis ipsam quas harum doloribus repellat, omnis quod autem? Distinctio id tempora ex doloremque reiciendis omnis aspernatur tempore ut veniam nemo et corrupti dolorem impedit quisquam adipisci, enim non ipsam provident? Iusto quia enim vel tempore qui quo consectetur soluta voluptatem.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos recusandae optio laborum facilis dolores vitae, quam aut! Eaque adipisci reprehenderit laboriosam, tempora dolores ab eius mollitia corporis atque delectus soluta voluptatibus recusandae pariatur voluptatum earum commodi aperiam reiciendis explicabo est veniam placeat consequatur eligendi nostrum ducimus! Sint atque, maxime accusamus adipisci fugit eum beatae nisi minus labore vel, reprehenderit ea ullam laboriosam. Excepturi at unde minus magnam veritatis dicta eius alias. Repellendus dolorem cum nam, odio esse rerum dolores modi quidem impedit reiciendis nesciunt, doloribus recusandae molestiae tempora, hic iure repudiandae. Aspernatur velit neque similique quasi odio obcaecati, dolorum eius.
                            </p>
                        </div>

                    </div>
                </section>
            </div>
        </>
    )
}


export async function getStaticProps(context: GetStaticPropsContext) {
    const { locale } = context;

    if (!locale) {
        throw new Error('Locale is not available in context');
    }

    return {
        props: {
            ... (await serverSideTranslations(locale, ['common', 'header']))
        }
    }
}
