import { GetStaticPropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from "next/head";
import styles from "@/styles/pages/foryou.module.scss";


export default function foryou() {


    return (

        <>
            <Head>
                <title>GEorGE • Cosmetic • For you</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charSet="UTF-8" />
                <meta name="az197" content="GEorGe Cosmetics" />
                {/* Keywords (specify relevant keywords related to your web page content for SEO): */}
                <meta name="keywords" content="keyword1, keyword2, keyword3" />
                <meta name="theme-color" content="#191716" />
            </Head>

            <div className={styles.ForyouPageWrapper}>


                <div className={styles.ForyouCard}>

                </div>

                <div className={styles.ForyouCard}>

                </div>

                <div className={styles.ForyouCard}>

                </div>

                <div className={styles.ForyouCard}>

                </div>

                <div className={styles.ForyouCard}>

                </div>

                <div className={styles.ForyouCard}>

                </div>
                
                <div className={styles.ForyouCard}>

                </div>
                
                <div className={styles.ForyouCard}>

                </div>
                
            </div>
        </>
    )
}


export async function getStaticProps(context: GetStaticPropsContext) {
    const { locale } = context;

    if (!locale) {
        throw new Error('Locale is not available in context');
    }

    return {
        props: {
            ... (await serverSideTranslations(locale, ['common', 'header']))
        }
    }
}
