import { Dropdown } from '@/components/CustomItems/Dropdown/Dropdown';
import { GetStaticPropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from "next/head";


export default function products() {


    return (
        <>
            <Head>
                <title>GEorGE • Cosmetic • Products</title>
                <link rel="icon" href="/george.ico" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charSet="UTF-8" />
                <meta name="az197" content="GEorGe Cosmetics" />
                {/* Keywords (specify relevant keywords related to your web page content for SEO): */}
                <meta name="keywords" content="keyword1, keyword2, keyword3" />
                <meta name="theme-color" content="#191716" />
            </Head>


            <div>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <h1>products</h1>
                <Dropdown />
            </div>
        </>
    )
}


export async function getStaticProps(context: GetStaticPropsContext) {
    const { locale } = context;

    if (!locale) {
        throw new Error('Locale is not available in context');
    }

    return {
        props: {
            ... (await serverSideTranslations(locale, ['common', 'header']))
        }
    }
}
